---
layout: post
category: Note
use_math: true
---

## 4/1 로그인/회원가입 구현

## django-allauth의 /account와 프로젝트 내 /account 충돌

초기 세팅에서 우리는 이미 account app을 생성했다. 하지만, Django-allauth도 내부의 account app이 있어서 usermodel이 충돌했다. 둘 중 하나를 바꿔야 했다.
```python
# setting.py
INSTALLED_APPS = [
    ...
    'account',
    ...

    # For allauth:
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    ...
```

이러면 *Application labels aren’t unique, duplicates: account* 오류가 뜬다. </br>
same label을 사용하고 있어서, accout에 unique한 label을 넣어줘야 한다.
```python
# account/apps.py
from django.apps import AppConfig


# class AccountConfig(AppConfig):
#     default_auto_field = 'django.db.models.BigAutoField'
#     name = 'account'

class AccountConfig(AppConfig):
    name = 'account'
    label = 'local_user'  # Change this
```

다음으로 **setting.py**도 변경해준다.
```python
# setting.py
INSTALLED_APPS = [
    ...
    'account.apps.AccountConfig', #change this from 'account'
    ...
]
```

하단에 usermodel도 변경해준다.
```python
# setting.py
AUTH_USER_MODEL = 'local_user.User'
```

이전의 *account*에서 migrate한 내용을 모두 삭제하고, 다시 migration 해주면 해결.